"""Weekly To Do List - an auto-generated priority list of which sites this
week's traps should go to, larvicide treatments, and larvae dipping/
inspection tasks for a given week.

This page is a thin UI layer over calc.build_weekly_todo_list, which is a
PURE, STATELESS view recomputed fresh from current data every time it's
called - see that function's docstring in core/calculations.py. There is no
"mark done" button anywhere on this page by design: a task is generated by a
rule (a trap still needing a site for the week, a treatment's control window
lapsing, an unresolved complaint or a single-signal hotspot needing
inspection) and it stops appearing the moment the related data - a new
surveillance event, treatment, or field observation - is logged elsewhere in
the app.
"""

import pandas as pd
import streamlit as st
from streamlit_folium import st_folium

from core import ui, calculations as calc, mapping
from core.config import (
    TODO_PRIORITY_HIGH, TODO_PRIORITY_MEDIUM, TODO_PRIORITY_COLOURS,
    TODO_TASK_TRAPPING, TODO_TASK_TREATMENT, TODO_TASK_DIPPING,
    MOSQUITO_SEASON_START_MONTH, MOSQUITO_SEASON_END_MONTH, WEEKLY_TRAP_COUNT,
)


def render():
    ui.apply_page_style()
    data = ui.get_data()
    filters = ui.render_global_filters(data)
    # The list is built only from the SELECTED SEASON's records (the season
    # filter, not its date range - a week is picked below). Without this, TEST
    # or a new season would show tasks generated from other seasons' data.
    season = filters["season"]
    for key in ("surv_events", "catch_totals", "complaints", "treatments", "observations", "larvae_dips"):
        data[key] = data[key][data[key]["Season"] == season]

    st.title("Weekly To Do List")
    ui.sample_data_banner()
    st.caption(f"Built from **{season}** records only (change the Season in the sidebar).")
    st.info(
        f"This list is generated automatically from complaints, recent trapping, larvae dip counts, hotspots and "
        f"treatment data - it is recomputed fresh every time this page loads, so **there is no 'mark done' "
        f"button**. A task drops off the list on its own the moment you log the surveillance event, treatment, "
        f"or field observation (a \"Larvae dip / inspection\" site observation, or an actual dip count, both on the Enter Data page) "
        f"it's asking for, elsewhere in the app. Trap placement assumes only "
        f"**{WEEKLY_TRAP_COUNT} CO2 traps** are available each week, set out for one night and picked up the "
        f"next morning."
    )

    # --- Week picker ---------------------------------------------------
    candidate_dates = pd.concat([
        data["surv_events"]["Deployment_DateTime"], data["treatments"]["Treatment_Date"],
        data["complaints"]["Date_Received"],
    ]).dropna()
    season_start, season_end = ui.SEASON_BOUNDS[season]
    today = pd.Timestamp.now().normalize()
    if season_start <= today <= season_end:
        default_ref_date = today.date()  # in-progress season: this week
    elif not candidate_dates.empty:
        default_ref_date = min(candidate_dates.max(), season_end).date()  # finished season: its last active week
    else:
        default_ref_date = season_start.date()

    ref_date = st.date_input(
        "Show priorities for the week containing", value=default_ref_date, key="todo_ref_date",
        help="Pick any date - the list always covers the full Monday-Sunday week it falls in.",
    )
    week_start = pd.Timestamp(ref_date) - pd.Timedelta(days=pd.Timestamp(ref_date).weekday())
    week_start = week_start.normalize()
    week_end = week_start + pd.Timedelta(days=6)
    st.caption(f"Week of **{week_start.date()} – {week_end.date()}**")

    if not (calc.is_in_mosquito_season(week_start) or calc.is_in_mosquito_season(week_end)):
        st.success(
            f"This week falls outside the mosquito season (October–May). The program doesn't operate "
            f"June–September, so no trapping, treatment or dipping actions are due. Pick a date between "
            f"{MOSQUITO_SEASON_START_MONTH} and {MOSQUITO_SEASON_END_MONTH} to see an in-season week."
        )
        st.stop()

    todo = calc.build_weekly_todo_list(
        week_start, data["sites"], data["surv_events"], data["catch_totals"], data["complaints"],
        data["treatments"], data["products"], data["thresholds"], data["observations"], data["larvae_dips"],
    )

    n_high = int((todo["Priority"] == TODO_PRIORITY_HIGH).sum()) if not todo.empty else 0
    n_trap = int((todo["Task_Type"] == TODO_TASK_TRAPPING).sum()) if not todo.empty else 0
    n_treat = int((todo["Task_Type"] == TODO_TASK_TREATMENT).sum()) if not todo.empty else 0
    n_dip = int((todo["Task_Type"] == TODO_TASK_DIPPING).sum()) if not todo.empty else 0

    ui.kpi_row([
        ("Total tasks", str(len(todo)), None),
        ("High priority", str(n_high), None),
        ("Trap sites to place", str(n_trap), f"Up to {WEEKLY_TRAP_COUNT} traps available this week."),
        ("Larvicide treatments", str(n_treat), None),
        ("Larvae dipping / inspection", str(n_dip), None),
    ])

    st.divider()

    if todo.empty:
        st.success(
            f"Nothing outstanding for this week - all {WEEKLY_TRAP_COUNT} traps have a site, and every "
            f"treatment and complaint/hotspot signal is up to date."
        )
        st.stop()

    c1, c2 = st.columns(2)
    with c1:
        task_filter = st.multiselect(
            "Filter by task type", [TODO_TASK_TRAPPING, TODO_TASK_TREATMENT, TODO_TASK_DIPPING],
            default=[TODO_TASK_TRAPPING, TODO_TASK_TREATMENT, TODO_TASK_DIPPING], key="todo_task_filter",
        )
    with c2:
        priority_filter = st.multiselect(
            "Filter by priority", [TODO_PRIORITY_HIGH, TODO_PRIORITY_MEDIUM],
            default=[TODO_PRIORITY_HIGH, TODO_PRIORITY_MEDIUM], key="todo_priority_filter",
        )
    view = todo[todo["Task_Type"].isin(task_filter) & todo["Priority"].isin(priority_filter)]

    if view.empty:
        st.info("No tasks match this filter selection.")
        st.stop()

    display = view.merge(data["sites"][["Site_ID", "Site_Name", "Site_Type"]], on="Site_ID", how="left")
    display["Site_Name"] = display["Site_Name"].fillna("(no specific site)")
    display["Due_Date"] = display["Due_Date"].apply(lambda d: d.date() if pd.notna(d) else "-")

    col_map, col_table = st.columns([2, 3])
    with col_map:
        st.markdown("**Task sites on the map**")
        week_hotspots = calc.identify_hotspots(
            data["catch_totals"], data["complaints"], data["treatments"], data["thresholds"], as_of=week_end,
            larvae_dips=data["larvae_dips"],
        )
        week_hotspot_by_site = {row["Site_ID"]: row for row in week_hotspots.to_dict("records")}
        statuses = [
            calc.site_map_status(sid, data["catch_totals"], data["thresholds"], hotspots_by_site=week_hotspot_by_site)
            for sid in data["sites"]["Site_ID"]
        ]
        status_df = pd.DataFrame(statuses)
        task_site_ids = set(view["Site_ID"].dropna())
        fmap = mapping.build_operational_map(
            data["sites"], status_df, hotspot_site_ids=task_site_ids,
            show_traps=True, show_complaints=False, show_treatments=False, show_hotspots_only=bool(task_site_ids),
        )
        st_folium(fmap, width=None, height=420)

    with col_table:
        st.markdown("**Priority list**")
        priority_order = {TODO_PRIORITY_HIGH: 0, TODO_PRIORITY_MEDIUM: 1}
        display["_sort"] = display["Priority"].map(priority_order)
        display = display.sort_values(["_sort", "Task_Type", "Site_Name"]).drop(columns="_sort")
        st.dataframe(
            display[["Priority", "Task_Type", "Site_Name", "Ref_ID", "Reason", "Due_Date"]],
            use_container_width=True, hide_index=True, height=420,
        )

    st.divider()
    st.subheader("How this list is built")
    st.caption(
        f"**Trap placement** recommends up to {WEEKLY_TRAP_COUNT} sites for this week's traps - confirmed "
        f"hotspots first (any 2 of trap/complaint/dip signals agreeing), then persistent elevated activity, then "
        f"any other flagged signal, then (once flagged sites run out) whichever candidate sites have gone "
        f"longest without a trap, so the whole network still gets rotated through over time. The recommendation "
        f"shrinks as sites are actually trapped this week (a logged surveillance event) and disappears once all "
        f"{WEEKLY_TRAP_COUNT} traps have a site. **Larvicide treatments** reuse the Re-dose schedule (Treatments "
        f"page) for sites with an existing tracked treatment, plus new hotspot sites with persistent trap "
        f"activity or a confirmed hotspot that have no tracked treatment yet, plus any site with an elevated "
        f"larvae dip count on its own (a measured high count is already an actionable signal, with no need for "
        f"trap/complaint corroboration first). **Larvae dipping/inspection** tasks come from unresolved "
        f"complaints (High once open a week or more) and from hotspot sites flagged by only ONE signal (a single "
        f"trap spike, or a complaint with no matching trap activity) - these are asked to be confirmed by "
        f"dipping before a treatment is scheduled. Logging the matching surveillance event, treatment, a "
        f"\"Larvae dip / inspection\" field observation, or an actual dip count all clear the matching task."
    )


render()
